name: Deploy Streamlit App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run the chatbot
      run: python chatbot.py

    - name: Deploy the app using Streamlit Sharing CLI
      run: |
        # Deploy the app using Streamlit Sharing CLI
        streamlit sharing deploy --token $STREAMLIT_SHARING_TOKEN
      env:
        STREAMLIT_SHARING_TOKEN: ${{ secrets.STREAMLIT_SHARING_TOKEN }}
